// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/getUserInfomation": {
            "post": {
                "description": "getAllInformation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getAllInformation"
                ],
                "summary": "getAllInformation",
                "parameters": [
                    {
                        "description": "requestUser",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.FileUserInformation"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.FileUserInformation": {
            "type": "object",
            "properties": {
                "createdTime": {
                    "type": "string"
                },
                "createdUserCode": {
                    "type": "string"
                },
                "lastModifiedTime": {
                    "type": "string"
                },
                "lastModifiedUserCode": {
                    "type": "string"
                },
                "newPath": {
                    "type": "string"
                },
                "originPath": {
                    "type": "string"
                }
            }
        },
        "models.RequestModel": {
            "type": "object",
            "required": [
                "paths"
            ],
            "properties": {
                "paths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
